version: '3.8'

services:
  login_register_users:
    image: login_register_users
    ports:
      - "8001:8001"
    networks:
      - databases_external_db_api

networks:
  databases_external_db_api:
    external: true