  version: '3.8'

  services:
    magazyn_stan:
      image: magazyn_stan
      ports:
        - "8005:8005"
      networks:
        - databases_external_db_api

  networks:
    databases_external_db_api:
      external: true