version: '3.8'

services:
  api:
    build:
      context: api
    env_file:
      - api/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres
    env_file:
      - postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data:

